// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tutorial7.Data;

#nullable disable

namespace Tutorial7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tutorial7.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU0000001",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "High-end desktop processor",
                            Name = "Intel Core i9-13900K"
                        },
                        new
                        {
                            Code = "RAM0000001",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 2,
                            Description = "DDR5 RAM module",
                            Name = "Kingston DDR5 32GB"
                        },
                        new
                        {
                            Code = "GPU0000001",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 3,
                            Description = "Top-tier graphics card",
                            Name = "NVIDIA RTX 4090"
                        });
                });

            modelBuilder.Entity("Tutorial7.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Intel",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        });
                });

            modelBuilder.Entity("Tutorial7.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        });
                });

            modelBuilder.Entity("Tutorial7.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Z",
                            Stock = 3,
                            Warranty = 48,
                            Weight = 18.0
                        });
                });

            modelBuilder.Entity("Tutorial7.Models.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "GPU0000001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RAM0000001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "CPU0000001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "RAM0000001",
                            Amount = 4
                        });
                });

            modelBuilder.Entity("Tutorial7.Models.Component", b =>
                {
                    b.HasOne("Tutorial7.Models.ComponentManufacturer", "Manufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutorial7.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Tutorial7.Models.PCComponent", b =>
                {
                    b.HasOne("Tutorial7.Models.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutorial7.Models.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("Tutorial7.Models.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("Tutorial7.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Tutorial7.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Tutorial7.Models.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
